Arithmetic Functions

In [64]:
import numpy as np
var = np.array([3,2,1,4,5,3,2])
print("min:",np.min(var))
print("position:",np.argmin(var))
print("max:",np.max(var))
print("position:",np.argmax(var))
print("sqrt:",np.sqrt(var))

min: 1
position: 2
max: 5
position: 4
sqrt: [1.73205081 1.41421356 1.         2.         2.23606798 1.73205081
 1.41421356]


In [68]:
varx = np.array([2,1,3])
print(np.sin(varx))
print(np.cos(varx))

[0.90929743 0.84147098 0.14112001]
[-0.41614684  0.54030231 -0.9899925 ]


2D 

In [62]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis = 0))

[2 1 3]


In [66]:
var2 = np.array([[2,1,3],[9,5,6]])
print(np.sin(var2))
print(np.cos(var2))

[[ 0.90929743  0.84147098  0.14112001]
 [ 0.41211849 -0.95892427 -0.2794155 ]]
[[-0.41614684  0.54030231 -0.9899925 ]
 [-0.91113026  0.28366219  0.96017029]]


In [70]:
var3 = np.array([4,5,6])
print(np.cumsum(var3))

[ 4  9 15]
