Arithmetic Operation

In [11]:
import numpy as np
var = np.array([1,2,3,4])
varadd = var + 3
print(varadd)

[4 5 6 7]


In [15]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varadd = var1 + var2
print(varadd)

[3 5 7 9]


In [17]:
import numpy as np
var = np.array([1,2,3,4])
varsub = var - 3
print(varsub)

[-2 -1  0  1]


In [19]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varsub = var1 - var2
print(varsub)

[-1 -1 -1 -1]


In [21]:
import numpy as np
var = np.array([1,2,3,4])
varmul = var * 3
print(varmul)

[ 3  6  9 12]


In [23]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varmul = var1 * var2
print(varmul)

[ 2  6 12 20]


In [27]:
import numpy as np
var = np.array([1,2,3,4])
vardivide = var/3
print(vardivide)

[0.33333333 0.66666667 1.         1.33333333]


In [29]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
vardivide = var1 / var2
print(vardivide)

[0.5        0.66666667 0.75       0.8       ]


In [31]:
import numpy as np
var = np.array([1,2,3,4])
varmod = var % 3
print(varmod)

[1 2 0 1]


In [35]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varmod = var1 % var2
print(varmod)

[1 2 3 4]


In [39]:
import numpy as np
var = np.array([1,2,3,4])
varpower = var ** 3
print(varpower)

[ 1  8 27 64]


In [41]:
var1 = np.array([1,2,3,4])
var2 = np.array([2,3,4,5])
varpower = var1 ** var2
print(varpower)

[   1    8   81 1024]


In [46]:
import numpy as np
var = np.array([1,2,3,4])
varrecipro = np.reciprocal(var)
print(varrecipro)

[1 0 0 0]


2D array

In [44]:
var11 = np.array([[2,3,4,5],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[4,5,6,7]])
varadd1 = var11 + var22
print(varadd1)

[[ 3  5  7  9]
 [ 5  7  9 11]]


In [48]:
var11 = np.array([[2,3,4,5],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[4,5,6,7]])
varsub1 = var11 - var22
print(varsub1)

[[ 1  1  1  1]
 [-3 -3 -3 -3]]


In [50]:
var11 = np.array([[2,3,4,5],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[4,5,6,7]])
varmul1 = var11 * var22
print(varmul1)

[[ 2  6 12 20]
 [ 4 10 18 28]]


In [52]:
var11 = np.array([[2,3,4,5],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[4,5,6,7]])
vardiv1 = var11 / var22
print(vardiv1)

[[2.         1.5        1.33333333 1.25      ]
 [0.25       0.4        0.5        0.57142857]]


In [54]:
var11 = np.array([[2,3,4,5],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[4,5,6,7]])
varmod1 = var11 % var22
print(varmod1)

[[0 1 1 1]
 [1 2 3 4]]


In [56]:
var11 = np.array([[2,3,4,5],[1,2,3,4]])
var22 = np.array([[1,2,3,4],[4,5,6,7]])
varpower1 = var11 ** var22
print(varpower1)

[[    2     9    64   625]
 [    1    32   729 16384]]
