In [15]:
import numpy as np
list1 = [10,20,30,40,50]
array1 = np.array(list1)
array1.ndim



1

In [19]:
import numpy as np
list1 = [[10,20,30],[40,50,60],[70,80,90]]
array1 = np.array(list1)
print(array1)
array1.shape

[[10 20 30]
 [40 50 60]
 [70 80 90]]


(3, 3)

In [21]:
import numpy as np
list1 = [[10,20,30],[40,50,60],[70,80,90]]
array1 = np.array(list1)
print(array1)
array1.size

[[10 20 30]
 [40 50 60]
 [70 80 90]]


9

In [25]:
import numpy as np
list1 = [[10,20,30,40]]
array1 = np.array(list1)
array1.dtype

dtype('int32')

In [27]:
import numpy as np
list1 = [20,30,35]
array1.itemsize

4