Broadcasting Array

In [75]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
varadd = np.add(a,b)
print(a)
print()
print(a.shape)
print()
print(varadd)

[1 2 3]

(3,)

[5 7 9]


In [77]:
x = np.array([[1],[2]])
print(x.shape)
print()
y = np.array([[1,2,3],[4,5,6]])
print(y.shape)
print()
print(x+y)

(2, 1)

(2, 3)

[[2 3 4]
 [6 7 8]]
