In [1]:
import numpy as np
array1 = np.arange(1,8)
print(array1)

[1 2 3 4 5 6 7]


In [3]:
import numpy as np
array1 = np.arange(11,17).reshape((2,3))
print(array1)

[[11 12 13]
 [14 15 16]]


In [5]:
import numpy as np
array1 = np.zeros(4)
print(array1)

[0. 0. 0. 0.]


In [9]:
import numpy as np
array1 = np.ones((3,2))
print(array1)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
