Shuffle


In [48]:
import numpy as np
var = np.array([1,2,3,4,5])
np.random.shuffle(var)
print(var)

[1 5 4 2 3]


Unique

In [51]:
var1 = np.array([1,2,3,4,2,5,2,6,2,7])
x = np.unique(var1)
print(x)

[1 2 3 4 5 6 7]


Resize

In [54]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


Flatten

In [63]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2,(2,3))
print(y)
print()
print(y.flatten(order = "F"))#column
print(y.flatten(order = "C"))#row
print(y.flatten(order = "A"))
print(y.flatten(order = "K"))


[[1 2 3]
 [4 5 6]]

[1 4 2 5 3 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]
[1 2 3 4 5 6]


Ravel

In [66]:
var2 = np.array([1,2,3,4,5,6])
y = np.resize(var2,(2,3))
print(y)
print()
print(np.ravel(y,order="A"))

[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]
