In [5]:
import numpy as np
var = np.array([1,2,3,4])
print(var)
v = np.insert(var,(2,4),6)
print(v)

[1 2 3 4]
[1 2 6 3 4 6]


Insert

In [11]:
var1 = np.array([[1,2,3],[1,2,3]])
v2 = np.insert(var1,2,6,axis = 0)
print(var1)
print()
print(v2)

[[1 2 3]
 [1 2 3]]

[[1 2 3]
 [1 2 3]
 [6 6 6]]


Append

In [15]:
import numpy as np
v = np.array([1,2,3,4,5])
print(v)
print()
v1 = np.append(v,6)
print(v1)

[1 2 3 4 5]

[1 2 3 4 5 6]


In [19]:
v2 = np.array([[1,2,3],[4,5,6]])
print(v2)
print()
v3 = np.append(v2,[[11,22,33]],axis=0)
print(v3)

[[1 2 3]
 [4 5 6]]

[[ 1  2  3]
 [ 4  5  6]
 [11 22 33]]


Delete

In [22]:
import numpy as np
var1 = np.array([1,2,3,4,5])
print(var1)
d = np.delete(var1,2)
print(d)