Iteration

In [80]:
import numpy as np
var = np.array([9,8,7,6,5,4,3])
print(var)
print()
for i in var:
    print(i)

[9 8 7 6 5 4 3]

9
8
7
6
5
4
3


In [82]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
    print(j)
print()
for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [84]:
var3 = np.array([[[9,8,7,6],[1,2,3,4]]])
print(var3)
print(var3.ndim)
print()
for i in np.nditer(var3):
    print(i)

[[[9 8 7 6]
  [1 2 3 4]]]
3

9
8
7
6
1
2
3
4
