Join Array


In [4]:
import numpy as np
var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])
ar = np.concatenate((var,var1))
print(ar)

[1 2 3 4 9 8 7 6]


In [12]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])
ar1 = np.concatenate((vr,vr1),axis=1)
print(vr)
print()
print(vr1)
print()
print(ar1)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2 9 8]
 [3 4 7 6]]


In [16]:
vr = np.array([[1,2],[3,4]])
vr1 = np.array([[9,8],[7,6]])
ar1 = np.concatenate((vr,vr1),axis=0)
print(vr)
print()
print(vr1)
print()
print(ar1)

[[1 2]
 [3 4]]

[[9 8]
 [7 6]]

[[1 2]
 [3 4]
 [9 8]
 [7 6]]


In [18]:
a = np.array([1,2,3,4])
b = np.array([9,8,7,6])
c = np.stack((a,b),axis = 0)
d = np.hstack((a,b)) #row
e = np.vstack((a,b)) #colums
f = np.dstack((a,b)) #height

print(c)
print()
print(d)
print()
print(e)
print()
print(f)

[[1 2 3 4]
 [9 8 7 6]]

[1 2 3 4 9 8 7 6]

[[1 2 3 4]
 [9 8 7 6]]

[[[1 9]
  [2 8]
  [3 7]
  [4 6]]]
