Matrix

In [2]:
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
print(var)
print(type(var))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [4]:
var1 = np.array([[1,2,3],[1,2,3]])
print(var1)
print(type(var1))


[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


Arithmetic opearation

In [7]:
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
var1 = np.matrix([[4,5,6],[3,4,5]])
print(var)
print(type(var))
print()
print(var + var1)

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>

[[5 7 9]
 [4 6 8]]


Multiplication

In [14]:
var1 = np.array([[4,5,6],[3,4,5]])
print(var1)
print(type(var1))
print()
print(var1*var1)

[[4 5 6]
 [3 4 5]]
<class 'numpy.ndarray'>

[[16 25 36]
 [ 9 16 25]]
