In [3]:
import numpy as np
var = np.array([[1,2,3,4,5],[6,7,8,9,1]])
print(var)
print()
print(var.shape)

[[1 2 3 4 5]
 [6 7 8 9 1]]

(2, 5)


In [5]:
var1 = np.array([[[[1,2,3],[1,2,3],[4,5,6],[2,3,4]]]])
print(var1)
print()
print(var1.ndim)
print()
print(var1.shape)


[[[[1 2 3]
   [1 2 3]
   [4 5 6]
   [2 3 4]]]]

4

(1, 1, 4, 3)


In [7]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print()
print(var2.ndim)
print()
x = var2.reshape(3,2)
print(x)
print(x.ndim)

[1 2 3 4 5 6]

1

[[1 2]
 [3 4]
 [5 6]]
2
