In [7]:
import numpy as np
array1 = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(array1[1,])
print(array1[:,1])
print(array1[1:3,])
print(array1[:,1:3])
print(array1[1:3,1])
print(array1[1:3,:1])

[40 50 60]
[20 50 80]
[[40 50 60]
 [70 80 90]]
[[20 30]
 [50 60]
 [80 90]]
[50 80]
[[40]
 [70]]
