In [3]:
import numpy as np
array1 = np.array([10,20,30,40,50,60,70])
print(array1[1:3])
print(array1[1:6:2])
print(array1[-1:-4:-1])
print(array1[::2])
print(array1[::2])
print(array1[::-1])


[20 30]
[20 40 60]
[70 60 50]
[10 30 50 70]
[10 30 50 70]
[70 60 50 40 30 20 10]
