Search

In [36]:
import numpy as np
var = np.array([1,2,3,4,2,5,2,5,6,7])
x = np.where(var == 2)
print(x)

(array([1, 4, 6], dtype=int64),)


Search sorted array

In [39]:
var1 = np.array([1,2,3,4,6,7,8,9,10])
x1 = np.searchsorted(var1,[5,6,7],side = "right")
print(x1)

[4 5 6]


Sort

In [42]:
a = np.array([4,5,3,2,7,8,6,11,9,10,15,20,33,1,0])
print(np.sort(a))

[ 0  1  2  3  4  5  6  7  8  9 10 11 15 20 33]


Filter Array

In [45]:
x = np.array([1,2,3,4])
f = [True,False,True,False]
new = x[f]
print(new)

[1 3]
