In [14]:
import numpy as np
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
import numpy as np
a = np.eye(3,5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [18]:
import numpy as np
a = np.linspace(1,10,num=5)
print(a)

[ 1.    3.25  5.5   7.75 10.  ]
